# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 71cc821aa187499f117799cbc067c2555a349698ba2f188b694a36dccc1fd82fcfa2a3f34c213abfb49b904708d267737fcb2f3d9a89fb528a07e483fe1d2c49

test:
  secret_key_base: 8902c059a564f61086795e92c3692d050b22117f24a98ccf4b0e5f0274c93595bc2055876b4f86f2a8640829a1eabb914066eec6ab594042b7199451104fcbe0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
